### ISSUE TITLE
Hazardous cargo (type) 

### ISSUE THREAD

**Issue by Rasbats** [Hakansv/AIS_VD_pi#3]
Not seeing this in the input screen. Has this been considered?

**Comment by Hakansv** [comment]
Yes, but what I can see in the IEC 61162-1:2016 standard there are no such parameter for the VSD message
Also the parameter 9) and 10) are omitted. I suppose all class A devices does not yet understand that? But it can easily be added if we decide so. Thoughts?
Håkan

Extract from: VSD – AIS voyage static data
![bild](https://user-images.githubusercontent.com/7202854/145681909-9133a6ca-a62f-487f-8da0-19e2bddd4d5e.png)

**Comment by Rasbats** [comment]
[http://www.annoyingdesigns.com/vsd/VSDControl.pdf](http://www.annoyingdesigns.com/vsd/VSDControl.pdf)

_Type of ship and cargo category_

I love the transparency of the IEC (Not).

**Comment by Hakansv** [comment]
Phuu... Comparing to your attached document I feel somewhat unprofessional (or Simplifying? 

As said "_Type of ship and cargo category_" is not Voyage static data, only static.

**Comment by Rasbats** [comment]
> As said "Type of ship and cargo category" is not Voyage static data, only static.

I should have looked at ref [6]: 

[https://www.navcen.uscg.gov/pdf/AIS/AISGuide.pdf](https://www.navcen.uscg.gov/pdf/AIS/AISGuide.pdf)

_7 – Reserved for future use_
Long time since I had to input this stuff. Closing.

**Comment by Rasbats** [comment]
[https://www.furunousa.com/-/media/sites/furuno/document_library/documents/manuals/public_manuals/fa170_operators_manual.pdf](https://www.furunousa.com/-/media/sites/furuno/document_library/documents/manuals/public_manuals/fa170_operators_manual.pdf)
Page 21.
I think it may be possible to enter shiptype with dg but  ...?

**Comment by Hakansv** [comment]
I may so but we don't want to interfere with static data. That can be set on the AIS device and I know there are some units with password protection for that kind of data. Furuno may interfere with there own device but not others, as we do.
