### ISSUE TITLE
Tarball version 

### ISSUE THREAD

**Issue by Hakansv** [Hakansv/AIS_VD_pi#6]
@leamas
Although the push is tagged the Tarball again has the Git number?
Uploading ais-vd-1.4.0+21.305ed06_msvc-10.0.14393-win32.tar.gz:
create mode 100644 metadata/ais-vd-1.4-msvc-10.0.14393.xml
Could a Tag be done in various ways?
```
C:\Builds\OCPN\ais-vd_pi>git tag -a -m "Version 1.4.0" 1.4.0
C:\Builds\OCPN\ais-vd_pi>git push origin master

```
[Buster build](https://app.circleci.com/pipelines/github/Hakansv/ais-vd_pi/20/workflows/818d0f13-e6b9-4283-aaf1-e7a6f75a706a/jobs/225)
[Win build](https://ci.appveyor.com/project/Hakansv/ais-vd-pi/builds/41921983)

![bild](https://user-images.githubusercontent.com/7202854/146444269-8a1af90d-778f-426e-b992-4456ff27719b.png)

**Comment by Hakansv** [comment]
![bild](https://user-images.githubusercontent.com/7202854/146446518-5b793544-31d7-4ecf-8742-abdaae197d0b.png)

BTW: Sorry for not using your icon but since you did all the hard work to make it load it was easy to edit a little.
Håkan

**Comment by leamas** [comment]
> Although the push is tagged the Tarball again has the Git number?

If so, it is a bug. I shall see if I can reproduce, but later....

Of course you should edit the icon, it was more of a placeholder than anything else.

**Comment by Hakansv** [comment]
Now learned.
After commit and push the Tag needs to be pushed separately.
Now clear and fine.

**Comment by leamas** [comment]
ah... :)

**Comment by leamas** [comment]
You can also push everything in one go using `git push --tags master:master` or so.

**Comment by Hakansv** [comment]
Ok, Thanks. I'll try that next time
